Repository nbcampMasterChapter3-3Team2/Beontteuk, pull requests merged in 2025-05, with the labels that each got.

#12 Feature: #6 gradient background color 적용
  Beontteuk/Presentation/Shared/Base/BaseView.swift
  Beontteuk/Presentation/Shared/Base/BaseViewController.swift
  Beontteuk/Presentation/Shared/Extension/Extension.swift
Labels: ⚙ Setting, 🐨 세준, ✨ Feature

#13 Feature: #8 - 공용으로 사용되는 UIBarButtomItem 구현
  Beontteuk/Presentation/Shared/ViewComponent/CustomUIBarButtonItem.swift
Labels: 🐨 세준, ✨ Feature

#14 Feature: #11 - 공용으로 사용되는 AddButton 구현
  Beontteuk/Presentation/Shared/ViewComponent/AddButton.swift
Labels: ✨ Feature, 🐺 다은

#16 Feature: #15 - 그림자 처리
  Beontteuk/Presentation/Shared/Extension/Extension.swift
  Beontteuk/Presentation/Shared/ViewComponent/CustomUIBarButtonItem.swift
Labels: ✨ Feature, 🐺 다은

#17 Feature:#10 - 공용으로 사용되는 DefaultButton 구현
  Beontteuk/Presentation/Shared/ViewComponent/DefaultButton.swift
Labels: ✨ Feature, 🦁 하경

#19 Feature:#9 - 스톱워치 UI 구현
  Beontteuk/Presentation/StopWatch/View/LapCell.swift
  Beontteuk/Presentation/StopWatch/View/StopWatchView.swift
  Beontteuk/Presentation/StopWatch/View/StopWatchViewController.swift
  Beontteuk/Presentation/StopWatch/ViewModel/StopWatchViewModel.swift
Labels: ✨ Feature, 🦁 하경

#21 Fix: #18 - 버튼에 그림자가 적용되지 않던 버그 해결
  Beontteuk/Presentation/Shared/Extension/Extension.swift
  Beontteuk/Presentation/Shared/ViewComponent/AddButton.swift
  Beontteuk/Presentation/Shared/ViewComponent/DefaultButton.swift
Labels: 🐞 BugFix

#22 Feature: #4 - 알람 UI 구현
  Beontteuk/Presentation/Alarm/BottomSheet/AlarmBottomSheetView.swift
  Beontteuk/Presentation/Alarm/BottomSheet/AlarmBottomSheetViewController.swift
  Beontteuk/Presentation/Alarm/Cell/AlarmBottomSheetTableViewCell.swift
  Beontteuk/Presentation/Alarm/Cell/AlarmTableViewHeaderCell.swift
  Beontteuk/Presentation/Alarm/Cell/AlarmTableViewListTypeCell.swift
  Beontteuk/Presentation/Alarm/View/AlarmView.swift
  Beontteuk/Presentation/Alarm/View/AlarmViewController.swift
  Beontteuk/Presentation/Alarm/ViewModel/AlarmViewModel.swift
  Beontteuk/Presentation/Shared/Base/BaseTableViewHeaderFooterView.swift
  Beontteuk/Presentation/Shared/ViewComponent/CustomUIBarButtonItem.swift
  Beontteuk/Presentation/Shared/ViewComponent/ShadowButton.swift
Labels: 🐨 세준, ✨ Feature

#26 [Feat] - CoreData Entity 작성, Repository 구현 및 유닛 테스트 작성
  Beontteuk.xcodeproj/project.pbxproj
  Beontteuk/App/AppDelegate.swift
  Beontteuk/App/SceneDelegate.swift
  Beontteuk/Beontteuk.xcdatamodeld/Beontteuk.xcdatamodel/contents
  Beontteuk/Data/Beontteuk.xcdatamodeld/.xccurrentversion
  Beontteuk/Data/Beontteuk.xcdatamodeld/Beontteuk.xcdatamodel/contents
  Beontteuk/Data/CoreData/CoreDataStack.swift
  Beontteuk/Data/Entity/Alarm/Alarm+CoreDataClass.swift
  Beontteuk/Data/Entity/Alarm/Alarm+CoreDataProperties.swift
  Beontteuk/Data/Entity/CDTimer/CDTimer+CoreDataClass.swift
  Beontteuk/Data/Entity/CDTimer/CDTimer+CoreDataProperties.swift
  Beontteuk/Data/Entity/LapRecord/LapRecord+CoreDataClass.swift
  Beontteuk/Data/Entity/LapRecord/LapRecord+CoreDataProperties.swift
  Beontteuk/Data/Entity/StopWatchSession/StopWatchSession+CoreDataClass.swift
  Beontteuk/Data/Entity/StopWatchSession/StopWatchSession+CoreDataProperties.swift
  Beontteuk/Data/Entity/WorldClock/WorldClock+CoreDataClass.swift
  Beontteuk/Data/Entity/WorldClock/WorldClock+CoreDataProperties.swift
  Beontteuk/Data/Repository/EmptyDataRepImp.swift
  Beontteuk/Data/Repository/Implementation/CoreDataAlarmRepository.swift
  Beontteuk/Data/Repository/Implementation/CoreDataCDTimerRepository.swift
  Beontteuk/Data/Repository/Implementation/CoreDataLapRecordRepository.swift
  Beontteuk/Data/Repository/Implementation/CoreDataStopWatchRepository.swift
  Beontteuk/Data/Repository/Implementation/CoreDataWorldClockRepository.swift
  Beontteuk/Data/WorldCity.json
  Beontteuk/Domain/Repository/Interface/AlarmRepositoryInterface.swift
  Beontteuk/Domain/Repository/Interface/CDTimerRepositoryInterface.swift
  Beontteuk/Domain/Repository/Interface/LapRecordRepositoryInterface.swift
  Beontteuk/Domain/Repository/Interface/StopWatchSessionRepositoryInterface.swift
  Beontteuk/Domain/Repository/Interface/WorldClockRepositoryInterface.swift
  BeontteukTests/Helpers/CoreDataAlarmRepositoryTests.swift
  BeontteukTests/Helpers/CoreDataStopWatchRepositoryTests.swift
  BeontteukTests/Helpers/CoreDataTestHelper.swift
  BeontteukTests/Helpers/CoreDataTimerRepositoryTests.swift
  BeontteukTests/Helpers/CoreDataWorldClockRepositoryTests.swift
Labels: ✨ Feature

#28 [Feat] - TabBarController 구현 및 CoreData Alarm → CDAlarm 리네이밍
  Beontteuk/App/SceneDelegate.swift
  Beontteuk/Data/Beontteuk.xcdatamodeld/Beontteuk.xcdatamodel/contents
  Beontteuk/Data/Entity/CDAlarm/CDAlarm+CoreDataClass.swift
  Beontteuk/Data/Entity/CDAlarm/CDAlarm+CoreDataProperties.swift
  Beontteuk/Data/Repository/Implementation/CoreDataAlarmRepository.swift
  Beontteuk/Domain/Repository/Interface/AlarmRepositoryInterface.swift
  Beontteuk/Presentation/Shared/Extension/Extension.swift
  Beontteuk/Presentation/TabBar/TabBarController.swift
  Beontteuk/Presentation/TabBar/TabBarItemType.swift
  Beontteuk/Presentation/ViewController.swift
  Beontteuk/Presentation/WorldClock/View/WorldClockViewController.swift
Labels: ✨ Feature, 🐯 래훈

#30 Feature: #2 - 타이머 UI 구현
  Beontteuk.xcodeproj/xcshareddata/xcschemes/Beontteuk.xcscheme
  Beontteuk/Presentation/Timer/View/Model/TimerItem.swift
  Beontteuk/Presentation/Timer/View/Subview/TimerAddHeader.swift
  Beontteuk/Presentation/Timer/View/Subview/TimerCurrentCell.swift
  Beontteuk/Presentation/Timer/View/Subview/TimerRecentCell.swift
  Beontteuk/Presentation/Timer/View/TimerView.swift
  Beontteuk/Presentation/Timer/View/TimerViewController.swift
  Beontteuk/Resources/Assets.xcassets/Color/primary200.colorset/Contents.json
Labels: ✨ Feature, 🐺 다은

#32 Feature: #25 - 알람 화면 View - ViewModel 데이터 바인딩
  Beontteuk/Presentation/Alarm/BottomSheet/AlarmBottomSheetView.swift
  Beontteuk/Presentation/Alarm/BottomSheet/AlarmBottomSheetViewController.swift
  Beontteuk/Presentation/Alarm/Cell/AlarmBottomSheetTableViewCell.swift
  Beontteuk/Presentation/Alarm/Cell/AlarmTableViewHeaderCell.swift
  Beontteuk/Presentation/Alarm/Cell/AlarmTableViewListTypeCell.swift
  Beontteuk/Presentation/Alarm/Common/AlarmSheetTableOption.swift
  Beontteuk/Presentation/Alarm/View/AlarmView.swift
  Beontteuk/Presentation/Alarm/View/AlarmViewController.swift
  Beontteuk/Presentation/Alarm/ViewModel/AlarmBottomSheetViewModel.swift
  Beontteuk/Presentation/Alarm/ViewModel/AlarmViewModel.swift
  Beontteuk/Presentation/Shared/Extension/Extension.swift
Labels: 🐨 세준, ✨ Feature, 🔨 Refactor

#34 [Feat] - 세계 시계 탭 UI 구성 및 Rx 바인딩 적용
  Beontteuk/Presentation/Shared/Extension/Extension.swift
  Beontteuk/Presentation/Shared/ViewComponent/AddButton.swift
  Beontteuk/Presentation/WorldClock/Cell/WorldClockTableHeaderView.swift
  Beontteuk/Presentation/WorldClock/Cell/WorldClockTableViewCell.swift
  Beontteuk/Presentation/WorldClock/View/WorldClockView.swift
  Beontteuk/Presentation/WorldClock/View/WorldClockViewController.swift
Labels: ✨ Feature, 🐯 래훈

#35 Feature: #24 - 스톱워치 버튼 상태 구현 및 공용 DefaultButton 수정
  Beontteuk/Presentation/Shared/ViewComponent/DefaultButton.swift
  Beontteuk/Presentation/StopWatch/View/LapCell.swift
  Beontteuk/Presentation/StopWatch/View/StopWatchView.swift
  Beontteuk/Presentation/StopWatch/View/StopWatchViewController.swift
  Beontteuk/Presentation/StopWatch/ViewModel/StopWatchViewModel.swift
Labels: ✨ Feature, 🔨 Refactor, 🦁 하경

#40 Feature: #31 - 타이머 추가 및 삭제 기능 구현
  Beontteuk/Data/Repository/Implementation/CoreDataCDTimerRepository.swift
  Beontteuk/Domain/Repository/Interface/CDTimerRepositoryInterface.swift
  Beontteuk/Domain/UseCase/Implementation/TimerUseImp.swift
  Beontteuk/Domain/UseCase/Interface/TimerUseInt.swift
  Beontteuk/Presentation/Shared/Base/EditableDataSource.swift
  Beontteuk/Presentation/TabBar/TabBarController.swift
  Beontteuk/Presentation/Timer/Model/TimerItem.swift
  Beontteuk/Presentation/Timer/View/Model/TimerItem.swift
  Beontteuk/Presentation/Timer/View/Subview/TimerActiveCell.swift
  Beontteuk/Presentation/Timer/View/Subview/TimerAddHeader.swift
  Beontteuk/Presentation/Timer/View/Subview/TimerRecentCell.swift
  Beontteuk/Presentation/Timer/View/TimerView.swift
  Beontteuk/Presentation/Timer/View/TimerViewController.swift
  Beontteuk/Presentation/Timer/ViewModel/TimerViewModel.swift
Labels: ✨ Feature, 🐺 다은

#41 Feature: #33 - 알람 CoreData CRUD 연동
  Beontteuk/Domain/UseCase/Implementation/AlarmUseImp.swift
  Beontteuk/Domain/UseCase/Interface/AlarmUseInt.swift
  Beontteuk/Presentation/Alarm/BottomSheet/AlarmBottomSheetViewController.swift
  Beontteuk/Presentation/Alarm/Cell/AlarmBottomSheetTableViewCell.swift
  Beontteuk/Presentation/Alarm/Cell/AlarmTableViewHeaderCell.swift
  Beontteuk/Presentation/Alarm/Cell/AlarmTableViewListTypeCell.swift
  Beontteuk/Presentation/Alarm/Common/AlarmSheetTableOption.swift
  Beontteuk/Presentation/Alarm/View/AlarmView.swift
  Beontteuk/Presentation/Alarm/View/AlarmViewController.swift
  Beontteuk/Presentation/Alarm/ViewModel/AlarmBottomSheetViewModel.swift
  Beontteuk/Presentation/Alarm/ViewModel/AlarmViewModel.swift
  Beontteuk/Presentation/Shared/ViewComponent/CustomUIBarButtonItem.swift
  Beontteuk/Presentation/TabBar/TabBarController.swift
Labels: 🐨 세준, ✨ Feature

#46 Feature: #42 - 타이머 핵심 기능 구현
  Beontteuk/Data/Repository/Implementation/CoreDataCDTimerRepository.swift
  Beontteuk/Domain/Entity/Entities.swift
  Beontteuk/Domain/Repository/Interface/CDTimerRepositoryInterface.swift
  Beontteuk/Domain/UseCase/Implementation/AlarmUseImp.swift
  Beontteuk/Domain/UseCase/Implementation/TimerUseImp.swift
  Beontteuk/Domain/UseCase/Interface/TimerUseInt.swift
  Beontteuk/Presentation/Shared/Notification/NotificationService.swift
  Beontteuk/Presentation/TabBar/TabBarController.swift
  Beontteuk/Presentation/Timer/Model/TimerItem.swift
  Beontteuk/Presentation/Timer/View/Subview/TimerActiveCell.swift
  Beontteuk/Presentation/Timer/View/Subview/TimerRecentCell.swift
  Beontteuk/Presentation/Timer/View/TimerView.swift
  Beontteuk/Presentation/Timer/View/TimerViewController.swift
  Beontteuk/Presentation/Timer/ViewModel/TimerViewModel.swift
  Beontteuk/Resources/mp3/dog-bark.wav
Labels: ✨ Feature, 🐺 다은

#47 Refactoring: #45 - 알람 관련 화면 코드 리펙토링
  Beontteuk/Data/Repository/Implementation/CoreDataAlarmRepository.swift
  Beontteuk/Domain/Entity/Entities.swift
  Beontteuk/Domain/Repository/Interface/AlarmRepositoryInterface.swift
  Beontteuk/Domain/UseCase/Implementation/AlarmUseImp.swift
  Beontteuk/Domain/UseCase/Interface/AlarmUseInt.swift
  Beontteuk/Presentation/Alarm/BottomSheetView/Cell/BottomSheetTableViewCell.swift
  Beontteuk/Presentation/Alarm/BottomSheetView/Model/BottomSheetSectionModel.swift
  Beontteuk/Presentation/Alarm/BottomSheetView/Model/BottomSheetTableOption.swift
  Beontteuk/Presentation/Alarm/BottomSheetView/View/AlarmBottomSheetView.swift
  Beontteuk/Presentation/Alarm/BottomSheetView/View/AlarmBottomSheetViewController.swift
  Beontteuk/Presentation/Alarm/BottomSheetView/ViewModel/AlarmBottomSheetViewModel.swift
  Beontteuk/Presentation/Alarm/Cell/AlarmTableViewCell.swift
  Beontteuk/Presentation/Alarm/Cell/AlarmTableViewHeader.swift
  Beontteuk/Presentation/Alarm/View/AlarmView.swift
  Beontteuk/Presentation/Alarm/View/AlarmViewController.swift
  Beontteuk/Presentation/Alarm/ViewModel/AlarmViewModel.swift
Labels: 🐨 세준, 🔨 Refactor

#50 Feature #37 - 스톱워치 기능 구현
  Beontteuk/Data/Entity/LapRecord/LapRecord+CoreDataProperties.swift
  Beontteuk/Data/Entity/StopWatchSession/StopWatchSession+CoreDataProperties.swift
  Beontteuk/Data/Repository/Implementation/CoreDataLapRecordRepository.swift
  Beontteuk/Data/Repository/Implementation/CoreDataStopWatchRepository.swift
  Beontteuk/Domain/Entity/Entities.swift
  Beontteuk/Domain/Repository/Interface/LapRecordRepositoryInterface.swift
  Beontteuk/Domain/Repository/Interface/StopWatchSessionRepositoryInterface.swift
  Beontteuk/Domain/UseCase/Implementation/LapRecordUseImp.swift
  Beontteuk/Domain/UseCase/Implementation/StopWatchUseImp.swift
  Beontteuk/Domain/UseCase/Interface/LapRecordUseInt.swift
  Beontteuk/Domain/UseCase/Interface/StopWatchUseInt.swift
  Beontteuk/Presentation/Shared/ViewComponent/DefaultButton.swift
  Beontteuk/Presentation/StopWatch/View/LapCell.swift
  Beontteuk/Presentation/StopWatch/View/StopWatchView.swift
  Beontteuk/Presentation/StopWatch/View/StopWatchViewController.swift
  Beontteuk/Presentation/StopWatch/ViewModel/Enum.swift
  Beontteuk/Presentation/StopWatch/ViewModel/StopWatchViewModel.swift
  Beontteuk/Presentation/TabBar/TabBarController.swift
Labels: ✨ Feature, 🦁 하경
